<a href="https://colab.research.google.com/github/EkeshwarSingh/hey_Git/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [6]:
arr1 = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]],

    [[13, 14, 15],
     [16, 17, 18]]
])

In [8]:
print(arr1)
type(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


numpy.ndarray

In [9]:
np.zeros(5)        # [0. 0. 0. 0. 0.]
np.ones((2, 3))    # 2x3 matrix of ones
np.arange(0, 10)   # 0 to 9
np.linspace(0, 1, 5)  # 5 equally spaced values


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr2 = np.arange(1, 100, 5)
print(arr2)
print(arr2.shape)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
(20,)


In [14]:
arr2_reshaped = arr2.reshape(5, 4)

In [16]:
print(arr2_reshaped)
print(arr2_reshaped.shape)

[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]
 [61 66 71 76]
 [81 86 91 96]]
(5, 4)
